App\Entity\BodyPart:
    type: entity
    table: body_part
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255