App\Domain\Dice\Entity\DiceType:
    type: entity
    table: dice_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value:
            unique: true
            type: integer