App\Domain\Gender\Entity\Gender:
    type: entity
    table: Gender
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value:
            type: integer