App\Domain\Game\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            unique: true
        description:
            type: text
        maxPlayer:
            type: integer
        creationDate:
            type: datetime
    oneToOne:
        masterPlayer:
            targetEntity: App\Domain\Player\Entity\Player
            cascade:
            - 'persist'
            fetch: LAZY
            mappedBy: gameMaster
    oneToMany:
        players:
            targetEntity: App\Domain\Player\Entity\Player
            cascade:
            - 'persist'
            fetch: LAZY
            mappedBy: game
        timer:
            targetEntity: App\Domain\Game\Entity\Timer
            cascade:
            - 'persist'
            fetch: LAZY
            mappedBy: game
