App\Domain\ObjectItem\Entity\ObjectItem:
    type: entity
    table: object_item
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        value:
            type: integer
    manyToMany:
        players:
            targetEntity: App\Domain\Player\Entity\Player
            mappedBy: objectItems

    manyToOne:
        diceType:
            targetEntity: App\Domain\Dice\Entity\DiceType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dice_type_id:
                    referencedColumnName: id
            orphanRemoval: false