App\Entity\ObjectType:
    type: entity
    table: object_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255