App\Domain\ObjectItem\Entity\ObjectItem:
    type: entity
    table: ObjectItem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        value:
            type: integer