App\Domain\Player\Entity\Player:
    type: entity
    table: Player
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        level:
            type: integer
        experience:
            type: integer
        life:
            type: integer
        maneuverability:
            type: integer
        attackPower:
            type: integer
        defense:
            type: integer
        parade:
            type: integer
        gold:
            type: integer
        picture:
            type: text
        inUse:
            type: boolean
    manyToOne:
        race:
            targetEntity: App\Domain\Race\Entity\Race
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                race_id:
                    referencedColumnName: id
            orphanRemoval: false

        game:
          targetEntity: App\Domain\Game\Entity\Game
          cascade:
          - 'persist'
          fetch: LAZY
          mappedBy: null
          inversedBy: players
          joinColumns:
            game_id:
              referencedColumnName: id
              nullable: false
          orphanRemoval: false
    oneToOne:
      gameMaster:
        targetEntity: App\Domain\Game\Entity\Game
        mappedBy: masterGame