App\Domain\Player\Entity\Player:
    type: entity
    table: User
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
        fields:
            title:
                type: integer
            level:
                type: integer
            experience:
                type: integer
            life:
                type: integer
            maneuverability:
                type: integer
            attackPower:
                type: integer
            defense:
                type: integer
            parade:
                type: integer
            gold:
                type: integer