App\Domain\Protection\Entity\Protection:
    type: entity
    table: protection
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        level:
            type: integer
    manyToMany:
        players:
            targetEntity: App\Domain\Player\Entity\Player
            mappedBy: protections

    manyToOne:
        diceType:
            targetEntity: App\Domain\Dice\Entity\DiceType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                dice_type_id:
                    referencedColumnName: id
            orphanRemoval: false