App\Domain\Race\Entity\Race:
    type: entity
    table: Race
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        coeff:
            type: integer
    oneToMany:
        players:
            targetEntity: App\Domain\Player\Entity\Player
            cascade:
              - 'persist'
            fetch: LAZY
            mappedBy: race