App\Entity\Timer:
    type: entity
    table: timer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        startDate:
            type: datetime
        endDate:
            nullable: true
            type: datetime
    manyToOne:
        game:
            targetEntity: App\Entity\Game
            cascade:
            - 'persist'
            fetch: LAZY
            mappedBy: timer
