App\Domain\Weapon\Entity\Weapon:
    type: entity
    table: weapon
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        strength:
            type: integer
    manyToMany:
        players:
            targetEntity: App\Domain\Player\Entity\Player
            mappedBy: weapons