App\Domain\Weapon\Entity\Weapon:
    type: entity
    table: Weapon
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        strength:
            type: integer